  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: actions/checkout@v2
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
        working-directory: src/client
      - name: Build app
        run: npm run build  
        working-directory: src/client
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        working-directory: src/client